name: Test

on: [push, pull_request, pull_request_target]

permissions:
  contents: read

jobs:
  echo_github:
    runs-on: ubuntu-24.04
    steps:
      - name: echo github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "${GITHUB_CONTEXT}"
  echo_event:
    runs-on: ubuntu-24.04
    steps:
      - name: echo event context
        run: |
          echo "${GITHUB_EVENT_PULL_REQUEST_HEAD_REPO_FULL_NAME}"
          echo "${GITHUB_EVENT_PULL_REQUEST_HEAD_REF}"
  echo_oops:
    #if: github.repository != 'steiltre/testing'
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    - name: do git stuff
      run: |
        git remote -v
        git branch --list
    - name: add to a file
      run: |
        echo "a" >> growing.txt
    - uses: EndBug/add-and-commit@v9
      with:
        author_name: Commit bot
        message: 'Committing'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  main_repo:
    if: github.repository == 'steiltre/testing'
    runs-on: ubuntu-24.04
    steps:
      - name: more printing
        run: |
          echo "Not appending to growing file on push to main repo"
